#test_hash:hash.o test_hash.o
#	@gcc -o test_hash hash.o test_hash.o
#	@echo doing compile test_hash

#test_hash.o:test_hash.c
#	@gcc -o test_hash.o -c test_hash.c
#	@echo doing compile test_hash.o
	
#hash.o:../utils/hash.c
#	@gcc -o hash.o -c ../utils/hash.c
#	@echo doing compile hash.o

#clean:
#	@rm -rf test_hash test_hash.o hash.o
#	@echo remove files !


#test_log:test_log.o log.o
#	@gcc -o test_log test_log.o log.o
#	@echo doing compile test_log
	
#test_log.o:test_log.c
#	@gcc -o test_log.o -c test_log.c
#	@echo doing compile test_log.o	
	
#log.o:../utils/log.c
#	@gcc -o log.o -c ../utils/log.c
#	@echo doing compile log.o
	
#clean:
#	@rm -rf test_log test_log.o log.o
#	@echo remove files !

test_list:test_list.o list.o
	@gcc -o test_list test_list.o list.o
	@echo doing compile test_list
	
test_list.o:test_list.c
	@gcc -o test_list.o -c test_list.c
	@echo doing compile test_list.o	
	
list.o:../utils/list.c
	@gcc -o list.o -c ../utils/list.c
	@echo doing compile list.o
	
clean:
	@rm -rf test_list test_list.o list.o
	@echo remove files !

	